config/routes.rb
Rails.application.routes.draw do
  match "/403", to: "errors#access_denied", via: :all, as: 'error_403'
  match "/404", to: "errors#not_found", via: :all, as: 'error_404'
  match "/500", to: "errors#internal_server_error", via: :all, as: 'error_500'

  # scope "(:locale)", locale: /en|es|eus/ do
  # scope "/:locale" do
  devise_for :users

  scope "/api" do
    get 'get_likes/:id', to: 'api#likes', as: 'get_likes'
    get 'get_place/:id', to: 'api#place', as: 'get_place'
  end

  get 'contact', to: 'messages#contact', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'register', to: 'messages#register', as: 'register'
  post 'register', to: 'messages#register_send'
  get "about_us", to: "static_pages#about_us", as: "about_us"
  get "all_maps", to: "places#maps", as: "all_maps"
  get "map/:id", to: "places#map", as: "map"
  get "search", to: "places#search", as: "search_places"
  post "votes", to: "votes#action", as: "votes_action"

  resources :places do
    resources :items
  end
  
 # WHY!!!!!?????
  resources :items

  namespace :admin do
    resources :places do
      resources :items do
        get "update_year", to: "items#update_year"
      end
    end
    resources :users
  end

  resources :clients
  root 'index#gps'
  get "index", to: "index#index", as: "index"
  # scope "(:locale)", locale: /en|es|eus/ do
  #   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #   # root 'index#index'
  #   get "index"
  # end

  # Error 404 route
  get '*pages', to: 'errors#not_found'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :place
  has_many :votes, dependent: :destroy
  # after_update_commit do
  #   ItemUpdateEventBroadcastJobJob.perform_later(self)
  # end

  def statistics
    males = 0
    females = 0
    votes.where(item_id: id).each do |vote|
      client = vote.client
      if client.gender == "male"
        males += 1
      elsif client.gender == "female"
        females += 1
      end
    end
    { males: males, females: females }
  end
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    # def show
    #   @place = Place.find(params[:place_id])
    #   @item = @place.items.find(params[:id])
    # end

    def new
      @place = Place.find(params[:place_id])
      @item = @place.items.build
      respond_to do |format|
        format.html # new.html.erb
        format.xml { render xml: @item }
        format.json { render json: @item }
      end
    end

    def edit
      @place = Place.find(params[:place_id])
      @item = @place.items.find(params[:id])
    end

    def create
      # @item = Item.new(params[:item])
      @place = Place.find(params[:place_id])
      @item = @place.items.build(item_params)
      @item.votes_count = 0
      respond_to do |format|
        if @item.save
          format.html { redirect_to admin_place_path(@place), success: 'Item created successfully.' }
          format.json { render json: @place, status: :created, location: @place }
        else
          format.html { render action: "new", error: "Item could not be created." }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @place = Place.find(params[:place_id])
      @item = @place.items.find(params[:id])

      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to admin_place_path(@place), success: 'Item updated successfully.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit", error: "Item could not be updated." }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @place = Place.find(params[:place_id])
      # @item = @place.items.delete(params[:id])
      respond_to do |format|
        if @place.items.delete(params[:id])
          format.html { redirect_to admin_place_path(@place), success: 'Item deleted successfully.' }
          format.json { head :no_content }
        else
          format.html { redirect_to admin_place_path(@place), error: "Item could not be deleted." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
      # @item.destroy
    end

    def update_year
      @place = Place.find(params[:place_id])
      @item = @place.items.find(params[:item_id])
      @votes = Vote.select(:client_id).where(item_id: @item.id, aviso: true)
      @clients = []
      @votes.each do |vote|
        @clients << Client.find(vote.client_id)
      end

      @clients.each do |client|
        MessageMailer.send_aviso(client, @item, @place).deliver
      end
      Vote.where(item_id: @item.id).update_all(aviso: false)
      @item.increment!("year", 1)
      redirect_to admin_place_path(@place)
    end

    private

      def item_params
        params.require(:item).permit(:name, :description, :picture, :year, :place_id, :votes_count)
      end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # WHY!!!!!?????
  def show
    @item = Item.find(params[:id])
    respond_to do |format|
      format.json { render json: @item }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= simple_form_for([:admin, @place, @item], class: 'contact_form') do |f| %>

    <label><%= t('labels.kupela.nombre') %></label><%= f.text_field :name, class: 'formulario', placeholder: 'Name', required: true %>
    <label><%= t('labels.kupela.descripcion') %></label><%= f.text_area :description, class: 'formulario', placeholder: 'Description', style: 'resize: vertical;' %>
    <label><%= t('labels.kupela.ano') %></label><%= f.number_field :year, class: 'formulario', placeholder: 'Year of the item', required: true %>
    <label><%= t('labels.kupela.foto') %></label><div id="foto2" name="foto2" class="formulario"><%= t('boton.selfoto') %></div>
        <%= f.hidden_field :picture, class: 'formulario', id: 'foto' %>
    <%= f.submit t('boton.guardar'), class: 'formulario', id: 'enviar' %>
<% end %>

app/views/admin/items/_item.html.erb
<tr>
    <td><img class="img-rounded img-kupela-lista" src="<%= item.picture %>" /></td>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= item.year %><br/>
    <%= link_to t('boton.embotellado'), admin_place_item_update_year_path(@place, item),
              data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
    </td>
    <td><%= link_to t('boton.editar'), edit_admin_place_item_path(@place, item), class: 'btn btn-primary' %></td>
	<td><%= link_to t('boton.eliminar'), admin_place_item_path(@place, item),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
    </td>
</tr>

app/views/admin/items/edit.html.erb
<div class="container-fluid content">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.editkupela') %></h1>
            </div>
            <div class="row">
                <%= render 'form' %>
                <!-- Los botones cancelar tienen que ir fuera del formulario-->
                <%= link_to "<button class='formulario' id='enviar'>#{t('boton.cancelar')}</button>".html_safe, admin_place_path(@place.id) %>
            </div>
        </div>
    </div>

app/views/admin/items/new.html.erb
<div class="container-fluid content">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.newkupela') %></h1>
            </div>
            <div class="row">
                <%= render 'form' %>
                <!-- Los botones cancelar tienen que ir fuera del formulario-->
                <%= link_to "<button class='formulario' id='enviar'>#{t('boton.cancelar')}</button>".html_safe, admin_place_path(@place.id) %>
            </div>
        </div>
    </div>