config/routes.rb
Rails.application.routes.draw do
  match "/403", to: "errors#access_denied", via: :all, as: 'error_403'
  match "/404", to: "errors#not_found", via: :all, as: 'error_404'
  match "/500", to: "errors#internal_server_error", via: :all, as: 'error_500'

  # scope "(:locale)", locale: /en|es|eus/ do
  # scope "/:locale" do
  devise_for :users

  scope "/api" do
    get 'get_likes/:id', to: 'api#likes', as: 'get_likes'
    get 'get_place/:id', to: 'api#place', as: 'get_place'
  end

  get 'contact', to: 'messages#contact', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'register', to: 'messages#register', as: 'register'
  post 'register', to: 'messages#register_send'
  get "about_us", to: "static_pages#about_us", as: "about_us"
  get "all_maps", to: "places#maps", as: "all_maps"
  get "map/:id", to: "places#map", as: "map"
  get "search", to: "places#search", as: "search_places"
  post "votes", to: "votes#action", as: "votes_action"

  resources :places do
    resources :items
  end
  
 # WHY!!!!!?????
  resources :items

  namespace :admin do
    resources :places do
      resources :items do
        get "update_year", to: "items#update_year"
      end
    end
    resources :users
  end

  resources :clients
  root 'index#gps'
  get "index", to: "index#index", as: "index"
  # scope "(:locale)", locale: /en|es|eus/ do
  #   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #   # root 'index#index'
  #   get "index"
  # end

  # Error 404 route
  get '*pages', to: 'errors#not_found'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :items, -> { order(name: :asc) }, dependent: :destroy
  has_many :users, -> { order(name: :asc) }, dependent: :destroy
  def self.search(search)
    where("name ILIKE ? OR town ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/admin/places_controller.rb
module Admin
  class PlacesController < ApplicationController
    before_filter :authenticate_user!
    load_and_authorize_resource
    def index
      @places = Place.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml { render xml: @places }
        format.json { render json: @places }
      end
    end

    def show
      @place = Place.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render xml: @place }
        format.json { render json: @place }
      end
    end

    def new
      @place = Place.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml { render xml: @place }
        format.json { render json: @place }
      end
    end

    def edit
      @place = Place.find(params[:id])
    end

    def create
      @place = Place.new(place_params)

      respond_to do |format|
        if @place.save
          format.html { redirect_to admin_places_path, success: 'Place created successfully.' }
          format.json { render json: @place, status: :created, location: @place }
        else
          format.html { render action: "new", error: "Place could not be created." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @place = Place.find(params[:id])

      respond_to do |format|
        if @place.update(place_params)
          format.html { redirect_to admin_place_path(@place), success: 'Place updated successfully.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit", error: "Place could not be updated." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @place = Place.find(params[:id])

      respond_to do |format|
        if @place.destroy
          format.html { redirect_to admin_places_path, success: 'Place deleted successfully.' }
          format.json { head :no_content }
        else
          format.html { redirect_to admin_places_path, error: "Place could not be deleted." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
      # index
    end

    private

      def place_params
        params.require(:place).permit(:name, :address, :latitude, :longitude, :description, :picture, :town, :time, :phone, :email)
      end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # before_filter :authenticate_user!
  # load_and_authorize_resource
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @places }
      format.json { render json: @places }
    end
  end

  def maps
    @places = Place.all
    # render 'all_maps'

    respond_to do |format|
      format.html { render action: "all_maps" }
      format.json { render json: @places }
    end
  end

  def map
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # map.html.erb
      format.xml { render xml: @place }
      format.json { render json: @place }
    end
  end

  def show
    @place = Place.find(params[:id])
    # @items = @place.items
    # @votes = Vote.all
    # @clients = Client.all
    # males = 0
    # females = 0
    # @item_data = []
    # # @item_dates = []
    # @items.each do |item|
    #   @votes.select(:client_id).where(item_id: item.id).each do |vote|
    #     client = @clients.find(vote.client_id)
    #     if client.gender == "male"
    #       males += 1
    #     elsif client.gender == "female"
    #       females += 1
    #     end
    #   end
    #   @item_data << { item_id: item.id, males: males, females: females }
    #   males = 0
    #   females = 0
    #   # @item_dates << @votes.group(:date).count
    # end
    # @item_data

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render xml: @place }
      format.json { render json: @place, include: [:items] }
    end
    # puts @item_dates
  end

  def search
    @places = Place.all
    if params[:search]
      @places = Place.search(params[:search]).order('name asc')
    else
      @places = Place.all.order('name asc')
    end
    render json: @places
  end
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/views/admin/places/_form.html.erb
<%= simple_form_for([:admin, @place], :class => 'contact_form') do |f| %>
<div class="row">   
    <div class="col-xs-4">
        <div class="row">
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.nombre') %></label><%= f.text_field :name, class: 'formulario', placeholder: 'Name', required: true %>
            </div>
        </div> 
        <div class="row">
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.foto') %></label><div id="foto2" name="foto2" class="formulario" value=""><%= t('boton.selfoto') %></div>
                <%= f.hidden_field :picture, class: 'formulario', id: 'foto' %>
            </div>
        </div>
    </div>
    <div class="col-xs-8">
        <div class="row">
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.descripcion') %></label><%= f.text_area :description, class: 'formulario', placeholder: 'Description', style: 'resize: vertical;' %>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.horario') %></label></textarea><%= f.text_area :time, class: 'formulario', placeholder: 'Opening time', style: 'resize: vertical;' %>
            </div>
        </div>
    </div>
</div>
<div class="row"> 
    <div class="col-xs-12">
        <label><%= t('labels.sidreria.ubicacion') %></label><div id="map" class="mapa mapaNSagar"></div>
    </div>
</div>
<div class="row"> 
    <div class="col-xs-6">
        <div class="row"> 
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.direccion') %></label><%= f.text_field :address, class: 'formulario', id: 'direccion', placeholder: 'Address', required: true %>
            </div>
        </div>
        <div class="row"> 
            <div class="col-xs-12">
                <%= f.text_field :town, class: 'formulario', id: 'pueblo', placeholder: 'Town', required: true %>
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="row"> 
            <div class="col-xs-12">
                <label><%= t('labels.sidreria.coordenadas') %></label><%= f.text_field :latitude, class: 'formulario', id: 'lat', placeholder: 'Latitude', required: true %>
            </div>
        </div>
        <div class="row"> 
            <div class="col-xs-12">
                <%= f.text_field :longitude, class: 'formulario', id: 'long', placeholder: 'Longitude', required: true %>
            </div>
        </div>
    </div>
</div>
<div class="row"> 
    <div class="col-xs-12">
        <%= f.submit t('boton.guardar'), class: 'formulario', id: 'enviar' %>
    </div>
</div>
<% end %>

app/views/admin/places/_place.html.erb
<tr>
    <td><%= place.id if place.id %></td>
    <td><%= place.name if place.name %></td>
    <td><%= place.address if place.address %></td>
    <td><%= place.description if place.description %></td>
    <td><%= link_to t('boton.manage'), admin_place_path(place), class: 'btn btn-default' %></td>
	<!-- <td><%= link_to t('boton.editar'), edit_admin_place_path(place), class: 'btn btn-default' %></td> -->
	<td><%= link_to t('boton.eliminar'), admin_place_path(place),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
</tr>

app/views/admin/places/edit.html.erb
<div class="container-fluid content">
    
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.editsidre') %></h1>
            </div>
        
            <div class="row">
                <%= render 'form' %>
                <%= link_to "<button class='formulario' id='enviar'>#{t('boton.cancelar')}</button>".html_safe, admin_place_path(@place.id) %>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
          <script>
          var map;
          var centro;
          var sidrerias = [];
        function myMap() {
            
            var perImg="<%= asset_path('personaPos.png') %>";
      		var persImg={
      			url:perImg,
      			size: new google.maps.Size(35, 35)
      		};

            var mapCanvas = document.getElementById("map");
            var mapOptions = {
                streetViewControl: true,
                mapTypeControl: true,
                zoomControl: true,
                center: new google.maps.LatLng(<%= @place.latitude %>,<%= @place.longitude %>),
                zoom: 15,
                scrollwheel: false
            };
            var map = new google.maps.Map(mapCanvas, mapOptions);

            var sidreria = new google.maps.Marker({
                position: new google.maps.LatLng(<%= @place.latitude %>,<%= @place.longitude %>),
                animation: google.maps.Animation.DROP,
                map: map,
                title: 'Tu sidrería.'
            });
            sidrerias.push(sidreria);
            setMapOnAll(map);
            
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                  var perPos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                  };
                  var persona = new google.maps.Marker({
                    position: perPos,
                    animation: google.maps.Animation.DROP,
                    map: map,
                    title: 'Tu posición.',
                    icon: persImg
                  });
                  map.setCenter(perPos);
                });
             }
            //Add listener
            new google.maps.event.addListener(map, "click", function (event) {
                var latitude = event.latLng.lat();
                var longitude = event.latLng.lng();
                //console.log( latitude + ', ' + longitude );
                $("#long").val(longitude);
                $("#lat").val(latitude);
                showPosition(latitude, longitude);
                
                setMapOnAll(null);
                sidrerias = [];

                var sidreria = new google.maps.Marker({
                    position: new google.maps.LatLng(latitude,longitude),
                    animation: google.maps.Animation.DROP,
                    map: map,
                    title: 'Tu sidrería.'
                });
                sidrerias.push(sidreria);
                setMapOnAll(map);
                
                
                
            }); //end addListener
    
          }
          
            function setMapOnAll(map) {
              for (var i = 0; i < sidrerias.length; i++) {
                sidrerias[i].setMap(map);
              }
            }
            
          
          function showPosition(lat,long) {
                var url2 = get_json("https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+long);
                var json2 = JSON.parse(url2);
                var a2 = json2.results[0].formatted_address;
                
                $("#direccion").val(a2);
                
                $.each(json2.results[0].address_components, function (i, address_component) {
                    if (address_component.types[0] == "locality"){
                        $("#pueblo").val(address_component.long_name);
                    }
                });
            }
            
            function get_json(url) {
                var resp ;
                var xmlHttp ;
                
                resp  = '' ;
                xmlHttp = new XMLHttpRequest();
                
                if(xmlHttp != null)
                {
                    xmlHttp.open( "GET", url, false );
                    xmlHttp.send( null );
                    resp = xmlHttp.responseText;
                }
                
                return resp ;
            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQWPiW2qkBRj4BXmEwFS2XMm2kzwKH82M&callback=myMap"></script>
    

app/views/admin/places/index.html.erb
<div class="container-fluid">
    <div class="row-nuevakupela" style="margin-top:50px;">
        <%= link_to new_admin_place_path, { :class => 'btn btn-default', :title => t('titulos.newsidre') } do %>
            <span class="glyphicon glyphicon-plus"></span>
        <% end %>
        
        <div class="table-responsive">
            <table id="usuarios" class="table table-hover">
                <tr>
                    <th>ID</th>
                    <th><%= t('labels.sidreria.nombre') %></th>
                    <th><%= t('labels.sidreria.direccion') %></th>
                    <th><%= t('labels.sidreria.descripcion') %></th>
                    <th colspan="2"><%= t('labels.sidreria.acciones') %></th>
                </tr>
                <%= render @places %>
            </table>
        </div>
    </div>

app/views/admin/places/new.html.erb
<div class="container-fluid content">
    
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.newsidre') %></h1>
            </div>
        
            <div class="row">
                <%= render 'form' %>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
          <script>
          var map;
          var centro;
          var sidrerias = [];
        function myMap() {
            
            var perImg="<%= asset_path('personaPos.png') %>";
      		var persImg={
      			url:perImg,
      			size: new google.maps.Size(35, 35)
      		};

            var mapCanvas = document.getElementById("map");
            var mapOptions = {
                streetViewControl: true,
                mapTypeControl: true,
                zoomControl: true,
                center: centro, 
                zoom: 15,
                scrollwheel: false
            };
            var map = new google.maps.Map(mapCanvas, mapOptions);
            
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                  var perPos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                  };
                  var persona = new google.maps.Marker({
                    position: perPos,
                    animation: google.maps.Animation.DROP,
                    map: map,
                    title: 'Tu posición.',
                    icon: persImg
                  });
                  map.setCenter(perPos);
                });
             }
            //Add listener
            new google.maps.event.addListener(map, "click", function (event) {
                var latitude = event.latLng.lat();
                var longitude = event.latLng.lng();
                //console.log( latitude + ', ' + longitude );
                $("#long").val(longitude);
                $("#lat").val(latitude);
                showPosition(latitude, longitude);
                
                setMapOnAll(null);
                sidrerias = [];

                var sidreria = new google.maps.Marker({
                    position: new google.maps.LatLng(latitude,longitude),
                    animation: google.maps.Animation.DROP,
                    map: map,
                    title: 'Tu sidrería.'
                });
                sidrerias.push(sidreria);
                setMapOnAll(map);
                
                
                
            }); //end addListener
    
          }
          
            function setMapOnAll(map) {
              for (var i = 0; i < sidrerias.length; i++) {
                sidrerias[i].setMap(map);
              }
            }
            
          
          function showPosition(lat,long) {
                var url2 = get_json("https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+long);
                var json2 = JSON.parse(url2);
                var a2 = json2.results[0].formatted_address;
                
                $("#direccion").val(a2);
                
                $.each(json2.results[0].address_components, function (i, address_component) {
                    if (address_component.types[0] == "locality"){
                        $("#pueblo").val(address_component.long_name);
                    }
                });
            }
            
            function get_json(url) {
                var resp ;
                var xmlHttp ;
                
                resp  = '' ;
                xmlHttp = new XMLHttpRequest();
                
                if(xmlHttp != null)
                {
                    xmlHttp.open( "GET", url, false );
                    xmlHttp.send( null );
                    resp = xmlHttp.responseText;
                }
                
                return resp ;
            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQWPiW2qkBRj4BXmEwFS2XMm2kzwKH82M&callback=myMap"></script>

    

app/views/admin/places/show.html.erb
<div class="container-fluid">
    <div class="container">
       <!-- <div class="row"> 
        <div class="col-md-3 col-lg-6 col-sm-3 ">
          <div id="chartContainer" style="height: 200px; width: 100%;"></div>
        </div>  
        <div class="col-md-3 col-lg-6 col-sm-3 ">
          <div id="chartContainer2" style="height: 200px; width: 100%;"></div> 
        </div> 
       </div>  -->
        <!-- {% for flashMessage in app.session.flashbag.get('mensaje') %}
        <div class="row">
          <div class="col-xs-12">
          	<div class="alert alert-success" role="alert">
          		<div class="container"> {{ flashMessage }} </div>
          	</div>
          </div>
        </div>
        {% endfor %} -->
        
        <div class="row">
          <div class="col-xs-12">
            <h1 class="page-header"><%= t('titulos.perfilsidre') %></h1>
            </div>
        </div>
        
        <div class="row">
          <div class="col-xs-6">
              <h1 class="card-title"><%= @place.name %></h1>
              <p class="card-description" id="descripcion"><%= @place.description %></p>
              <p class="card-description" id="horario"><%= @place.time %></p>
              <%= link_to t('boton.editar'), edit_admin_place_path(@place), class: 'btn btn-primary' %>
         </div>
         <div class="col-xs-6">
           <div class="card-single-direction text-uppercase text-center"><h4><%= @place.town %></h4></div>
           <img src= "<%= @place.picture %>"  class="img-responsive single-img img-rounded" alt="Responsive image">
          </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-9 col-xs-offset-1">
          <h2 class="page-header"><%= t('titulos.listakupelas') %></h2>
        </div>
        <div class="col-xs-1">
            <div class="add-kupela pull-right">
            <%= link_to new_admin_place_item_path(@place.id) do %>
                <i id= "plus" class="fa fa-plus-square-o fa-4x" aria-hidden="true"></i></a>
            <% end %>
            </div>
        </div>  
        <div class="col-xs-10 col-xs-offset-1">
            
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th><%= t('labels.kupela.foto') %></th>
                    <th><%= t('labels.kupela.nombre') %></th>
                    <th><%= t('labels.kupela.descripcion') %></th>
                    <th><%= t('labels.kupela.ano') %></th>
                    <th colspan="2">Actions:</th>
                  </tr>
                </thead>
                <tbody>
                  <%= render @place.items %>
                </tbody>
              </table>             
            </div>
        </div>
    </div>

      
      

      <!-- <script src={{asset("js/estadisticas.min.js")}}></script>
      <script type="text/javascript">
      
      window.onload = function () {
      	var chart = new CanvasJS.Chart("chartContainer", {
      		theme: "theme2",//theme1
      		title:{
      			text: "Likes a las kupelas por GENERO"              
      		},
      		animationEnabled: false,   // change to true
      		data: [              
      		{
      			// Change type to "bar", "area", "spline", "pie",etc.
      			type: "pie",
      			dataPoints: [
      				{ label: "Mujeres",  y: {{mujeres[0].mujeres}}},
      				{ label: "Hombres", y: {{hombres[0].hombres}}}
      				
      			]
      		}
      		]
      	});
      	chart.render();
        	
        	
        	
      	var chart2 = new CanvasJS.Chart("chartContainer2", {
      		theme: "theme2",//theme1
      		title:{
      			text: "Numero Votos por fecha"              
      		},
      		animationEnabled: false,   // change to true
      		data: [              
      		{
      			// Change type to "bar", "area", "spline", "pie",etc.
      			type: "column",
      			dataPoints: [
      			  {% for fecha in fechas %}
      			    	{ label: "{{fecha.fecha | date("d/m/Y")}}",  y: {{fecha.NumVotos}} },
      			  {% endfor %}
      	
      			]
      		}
      		]
      	});
      	chart2.render();
      }
      </script> -->