config/routes.rb
Rails.application.routes.draw do
  match "/403", to: "errors#access_denied", via: :all, as: 'error_403'
  match "/404", to: "errors#not_found", via: :all, as: 'error_404'
  match "/500", to: "errors#internal_server_error", via: :all, as: 'error_500'

  # scope "(:locale)", locale: /en|es|eus/ do
  # scope "/:locale" do
  devise_for :users

  scope "/api" do
    get 'get_likes/:id', to: 'api#likes', as: 'get_likes'
    get 'get_place/:id', to: 'api#place', as: 'get_place'
  end

  get 'contact', to: 'messages#contact', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'register', to: 'messages#register', as: 'register'
  post 'register', to: 'messages#register_send'
  get "about_us", to: "static_pages#about_us", as: "about_us"
  get "all_maps", to: "places#maps", as: "all_maps"
  get "map/:id", to: "places#map", as: "map"
  get "search", to: "places#search", as: "search_places"
  post "votes", to: "votes#action", as: "votes_action"

  resources :places do
    resources :items
  end
  
 # WHY!!!!!?????
  resources :items

  namespace :admin do
    resources :places do
      resources :items do
        get "update_year", to: "items#update_year"
      end
    end
    resources :users
  end

  resources :clients
  root 'index#gps'
  get "index", to: "index#index", as: "index"
  # scope "(:locale)", locale: /en|es|eus/ do
  #   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #   # root 'index#index'
  #   get "index"
  # end

  # Error 404 route
  get '*pages', to: 'errors#not_found'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :place
  belongs_to :role

  # attr_accessor :password, :password_confirmation
  # validates_presence_of :name
  before_save :assign_role

  def admin?
    self.role.name == "Admin"
  end

  def assign_role
    self.role = Role.find_by name: "Seller" if self.role.nil?
  end

  def seller?
    self.role.name == "Seller"
  end

  # def regular?
  #   self.role.name == "Regular"
  # end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    # before_filter :authenticate_user!
    # devise :database_authenticatable, :registerable,
    #        :recoverable, :rememberable, :trackable, :validatable
    before_action :authenticate_user!
    load_and_authorize_resource
    # after_action :load_and_authorize_resource
    # load_and_authorize_resource

    def index
      @users = User.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml { render xml: @users }
        format.json { render json: @users }
      end
    end

    def show
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.xml { render xml: @user }
        format.json { render json: @user }
      end
    end

    def new
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml { render xml: @user }
        format.json { render json: @user }
      end
    end

    def create
      # @user = user.new(user_params)
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to admin_users_path, success: 'User created successfully.' }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: "new", error: "User could not be created." }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
      # render plain: params[:user].inspect
    end

    def edit
      # authorize! :edit, @user
      @user = User.find(params[:id])
    end

    # def update
    #   @user = User.find(params[:id])

    #   if @user.update(user_params)
    #     redirect_to admin_users_path
    #   else
    #     render 'edit'
    #   end
    # end

    def destroy
      @user = User.find(params[:id])

      respond_to do |format|
        if @user.destroy
          format.html { redirect_to admin_users_path, success: 'User deleted successfully.' }
          format.json { head :no_content }
        else
          format.html { redirect_to admin_users_path, error: "User could not be deleted." }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
      # index
    end

    def update
      @user = User.find(params[:id])
      if user_params[:password].blank?
        @user.update_without_password(user_params)
      else
        @user.update_attributes(user_params)
      end

      respond_to do |format|
        if @user.errors.blank?
          if current_user.role == "admin"
            format.html { redirect_to admin_users_path, success: 'User updated successfully.' }
          else
            format.html { redirect_to index_path, success: 'User updated successfully.' }
          end
          format.json { head :no_content }
        else
          format.html { render action: "edit", error: "User could not be updated." }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :surnames, :address, :phone, :role_id, :place_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<!--<%= debug @user.errors %>-->
<%= simple_form_for([:admin, @user], :class => 'contact_form') do |f| %>
<!--<%= f.input :name %>-->
    <label><%= t('labels.usuario.nombre') %></label><%= f.text_field :name, class: 'formulario', placeholder: 'Name', required: true %>
    <label><%= t('labels.usuario.apellidos') %></label><%= f.text_field :surnames, class: 'formulario', placeholder: 'Surnames' %>
    <label><%= t('labels.usuario.email') %></label><%= f.email_field :email, class: 'formulario', placeholder: 'Email', required: true %>
    <% if user_signed_in? && current_user.admin? %>
        <label><%= t('labels.usuario.sidreria') %></label><%= f.collection_select(:place_id, Place.all, :id, :name, {prompt: true}, class: 'formulario') %>
        <label>Role:</label><%= f.collection_select(:role_id, Role.all, :id, :name, {prompt: true}, class: 'formulario') %>
    <% end %>
    <label><%= t('labels.usuario.telefono') %></label><%= f.telephone_field :phone, class: 'formulario', placeholder: 'Phone', required: true %>
    <label>Address:</label><%= f.text_field :address, class: 'formulario', placeholder: 'Address', required: true %>
    <% if @user.persisted? %>
        <label>Password:</label> <%= f.password_field :password, class: 'formulario', placeholder: 'Password (Leave blank if unchanged)' %>
        <label>Password Confirmation:</label> <%= f.password_field :password_confirmation, class: 'formulario', placeholder: 'Repeat password (Leave blank if unchanged)' %>
    <% else %>
        <label>Password:</label> <%= f.password_field :password, class: 'formulario', placeholder: 'Password', required: true %>
        <label>Password Confirmation:</label> <%= f.password_field :password_confirmation, class: 'formulario', placeholder: 'Repeat password', required: true %>
    <% end %>
    <%= f.submit t('boton.guardar'), class: 'formulario', id: 'enviar' %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
	<td><%= user.id if user.id %></td>
	<td><%= user.name if user.name %> <%= user.surnames if user.surnames %></td>
	<td><%= user.place.name if user.place_id %></td>
	<td><%= user.email if user.email %></td>
	<td><%= user.phone if user.phone %></td>
	<td><%= link_to t('boton.mostrar'), admin_user_path(user), class: 'btn btn-default' %></td>
	<td><%= link_to t('boton.editar'), edit_admin_user_path(user), class: 'btn btn-default' %></td>
	<td><%= link_to t('boton.eliminar'), admin_user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
</tr>

app/views/admin/users/edit.html.erb
<div class="container-fluid content">
    
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.editusuario') %></h1>
            </div>
        
            <div class="row">
                <%= render "form" %>
            </div>
        </div>
    </div>

app/views/admin/users/index.html.erb
<div class="container-fluid">
    <% if flash[:notice] %>
        <div class="notice alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:success] %>
        <div class="notice alert alert-success"><%= flash[:success] %></div>
    <% end %>
    <% if flash[:error] %>
        <div class="notice alert alert-danger"><%= flash[:error] %></div>
    <% end %>
    <div class="row-nuevakupela" style="margin-top:50px;">
        <%= link_to 'users/new', { :class => 'btn btn-default', :title => t('titulos.newusuario') } do %>
            <span class="glyphicon glyphicon-plus"></span>
        <% end %>
        <div class="table-responsive">
            <table id="usuarios" class="table table-hover">
                <tr>
                    <th>ID</th>
                    <th><%= t('labels.usuario.nombre') %></th>
                    <th><%= t('labels.usuario.sidreria') %></th>
                    <th><%= t('labels.usuario.email') %></th>
                    <th><%= t('labels.usuario.telefono') %></th>
                    <th colspan="3"><%= t('labels.usuario.acciones') %></th>
                </tr>
                <%= render @users %>
            </table>
        </div>
    </div>

app/views/admin/users/new.html.erb
<div class="container-fluid content">
    
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="row">
                <h1 class="mtitle title-padding text-center"><%= t('titulos.newusuario') %></h1>
            </div>
        
            <div class="row">
                <%= render "form" %>
            </div>
        </div>
    </div>

app/views/admin/users/show.html.erb
<div class="container-fluid content">
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <h3>User</h3>
            <table>
                <tr>
                    <th><%= t('labels.usuario.nombre') %></th>
                    <td><%= @user.name if @user.name %></td>
                </tr>
                <tr>
                    <th><%= t('labels.usuario.apellidos') %></th>
                    <td><%= @user.surnames if @user.surnames %></td>
                </tr>
                <tr>
                    <th><%= t('labels.usuario.email') %></th>
                    <td><%= @user.email if @user.email %></td>
                </tr>
                <tr>
                    <th><%= t('labels.usuario.sidreria') %></th>
                    <td><%= @user.place.name if @user.place_id %></td>
                </tr>
                <tr>
                    <th>Role:</th>
                    <td><%= @user.role.name if @user.role_id %></td>
                </tr>
                <tr>
                    <th><%= t('labels.usuario.telefono') %></th>
                    <td><%= @user.phone if @user.phone %></td>
                </tr>
                <tr>
                    <th>Address:</th>
                    <td><%= @user.address if @user.address %></td>
                </tr>
            </table>
        </div>
    </div>