config/routes.rb
Rails.application.routes.draw do
  match "/403", to: "errors#access_denied", via: :all, as: 'error_403'
  match "/404", to: "errors#not_found", via: :all, as: 'error_404'
  match "/500", to: "errors#internal_server_error", via: :all, as: 'error_500'

  # scope "(:locale)", locale: /en|es|eus/ do
  # scope "/:locale" do
  devise_for :users

  scope "/api" do
    get 'get_likes/:id', to: 'api#likes', as: 'get_likes'
    get 'get_place/:id', to: 'api#place', as: 'get_place'
  end

  get 'contact', to: 'messages#contact', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'register', to: 'messages#register', as: 'register'
  post 'register', to: 'messages#register_send'
  get "about_us", to: "static_pages#about_us", as: "about_us"
  get "all_maps", to: "places#maps", as: "all_maps"
  get "map/:id", to: "places#map", as: "map"
  get "search", to: "places#search", as: "search_places"
  post "votes", to: "votes#action", as: "votes_action"

  resources :places do
    resources :items
  end
  
 # WHY!!!!!?????
  resources :items

  namespace :admin do
    resources :places do
      resources :items do
        get "update_year", to: "items#update_year"
      end
    end
    resources :users
  end

  resources :clients
  root 'index#gps'
  get "index", to: "index#index", as: "index"
  # scope "(:locale)", locale: /en|es|eus/ do
  #   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #   # root 'index#index'
  #   get "index"
  # end

  # Error 404 route
  get '*pages', to: 'errors#not_found'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :items, -> { order(name: :asc) }, dependent: :destroy
  has_many :users, -> { order(name: :asc) }, dependent: :destroy
  def self.search(search)
    where("name ILIKE ? OR town ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/admin/places_controller.rb
module Admin
  class PlacesController < ApplicationController
    before_filter :authenticate_user!
    load_and_authorize_resource
    def index
      @places = Place.all

      respond_to do |format|
        format.html # index.html.erb
        format.xml { render xml: @places }
        format.json { render json: @places }
      end
    end

    def show
      @place = Place.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render xml: @place }
        format.json { render json: @place }
      end
    end

    def new
      @place = Place.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml { render xml: @place }
        format.json { render json: @place }
      end
    end

    def edit
      @place = Place.find(params[:id])
    end

    def create
      @place = Place.new(place_params)

      respond_to do |format|
        if @place.save
          format.html { redirect_to admin_places_path, success: 'Place created successfully.' }
          format.json { render json: @place, status: :created, location: @place }
        else
          format.html { render action: "new", error: "Place could not be created." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      @place = Place.find(params[:id])

      respond_to do |format|
        if @place.update(place_params)
          format.html { redirect_to admin_place_path(@place), success: 'Place updated successfully.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit", error: "Place could not be updated." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @place = Place.find(params[:id])

      respond_to do |format|
        if @place.destroy
          format.html { redirect_to admin_places_path, success: 'Place deleted successfully.' }
          format.json { head :no_content }
        else
          format.html { redirect_to admin_places_path, error: "Place could not be deleted." }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      end
      # index
    end

    private

      def place_params
        params.require(:place).permit(:name, :address, :latitude, :longitude, :description, :picture, :town, :time, :phone, :email)
      end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # before_filter :authenticate_user!
  # load_and_authorize_resource
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @places }
      format.json { render json: @places }
    end
  end

  def maps
    @places = Place.all
    # render 'all_maps'

    respond_to do |format|
      format.html { render action: "all_maps" }
      format.json { render json: @places }
    end
  end

  def map
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # map.html.erb
      format.xml { render xml: @place }
      format.json { render json: @place }
    end
  end

  def show
    @place = Place.find(params[:id])
    # @items = @place.items
    # @votes = Vote.all
    # @clients = Client.all
    # males = 0
    # females = 0
    # @item_data = []
    # # @item_dates = []
    # @items.each do |item|
    #   @votes.select(:client_id).where(item_id: item.id).each do |vote|
    #     client = @clients.find(vote.client_id)
    #     if client.gender == "male"
    #       males += 1
    #     elsif client.gender == "female"
    #       females += 1
    #     end
    #   end
    #   @item_data << { item_id: item.id, males: males, females: females }
    #   males = 0
    #   females = 0
    #   # @item_dates << @votes.group(:date).count
    # end
    # @item_data

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render xml: @place }
      format.json { render json: @place, include: [:items] }
    end
    # puts @item_dates
  end

  def search
    @places = Place.all
    if params[:search]
      @places = Place.search(params[:search]).order('name asc')
    else
      @places = Place.all.order('name asc')
    end
    render json: @places
  end
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/views/places/_facebook.html.erb
<div id="fb-root"></div>

<script>

window.fbAsyncInit = function() {
    // iniciamos la aplicación de Facebook
    FB.init({
        appId      : '<%= ENV['FACEBOOK_KEY'] %>',
        status     : true,
        xfbml      : true,
        cookie     : true
    });
    
    // si no está conectado, muestra la ventana de conexión
    $(document).on("click", ".btn-facebook, .btn-aviso", function(){
        var idItem = $(this).data('numero');
        var button = $(this).data('button');
        FB.getLoginStatus(function(response) {
            if (response.status === 'connected') {
                getAPI(idItem, button);
            } else {
                fb_login(idItem, button);
            }
        });
    });
};

(function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/all.js";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

function fb_login(idItem, button){
    FB.login(function(response){
        if (response.authResponse){
            getAPI(idItem, button);
        }
    }, {"scope":"email,user_birthday,user_location"});
}

function getAPI(idItem, button){
    // obtiene información del usuario y la muestra
    FB.api("/me?fields=id,name,email,age_range,birthday,gender,location", function(response){
        window.fb_user = response.id;
        // Hace la llamada AJAX
        $.ajax({
            type: "POST",
            dataType: "json",
            url: "<%= votes_action_path %>",
            data: {response, item_id: idItem, button: button }
        });
    });
    // App.item.update({votes: idItem});
}

</script>

app/views/places/_list.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1 class="mtitle text-center"><%= t('paginas.sidrerias.titulo') %></h1>
    </div>
    <% @places.each do |place| %>
    
    <div class="col-xs-6 col-lg-4">
        <div class="card">
        	<%= link_to place_path(place), { :class => 'card-link', :name => place.name } do %>
	            <div class="card-direction text-uppercase text-center"><h4><%= place.town %></h4></div>
	            <img class="card-image img-responsive" src="<%= place.picture %>"></img>
	            <h2 class="card-title text-uppercase"><%= place.name %></h2>
	            <p class="card-description"><%= place.description %></p>
            <% end %>
        </div>
    </div>
    <% end %>
</div>

app/views/places/all_maps.html.erb
<div class="container-fluid">
	<%= render 'all_maps' %>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQWPiW2qkBRj4BXmEwFS2XMm2kzwKH82M&callback=myMap"></script>

app/views/places/index.html.erb
<div class="container-fluid">
    <%= render "list.html.erb" %>

app/views/places/map.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-12">
        <h1 class="text-center mtitle a-sagar"><%= link_to @place.name, place_path(@place.id) %></h1>
    </div>
    <div class="col-md-12">
      <div id="map" class="mapa"></div>
  
          <script>
          window.onload = function(){
            if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|BB|PlayBook|IEMobile|Windows Phone|Kindle|Silk|Opera Mini/i.test(navigator.userAgent)) {
              window.location = "google.navigation:q=<%= @place.latitude %>,<%= @place.longitude %>";
            }
          }
          
          var map;
          var user;
          var centerControlDiv = document.createElement('div');
          var centerControlDiv2 = document.createElement('div');
          var mv = 0;
  
  
        function CenterControl(controlDiv, map, persona) {
        
          // Set CSS for the control border.
          var firstChild = document.createElement('button');
            firstChild.style.backgroundColor = '#fff';
            firstChild.style.border = 'none';
            firstChild.style.outline = 'none';
            firstChild.style.width = '28px';
            firstChild.style.height = '28px';
            firstChild.style.borderRadius = '2px';
            firstChild.style.boxShadow = '0 1px 4px rgba(0,0,0,0.3)';
            firstChild.style.cursor = 'pointer';
            firstChild.style.marginRight = '10px';
            firstChild.style.padding = '0px';
            firstChild.title = 'Your Location';
            controlDiv.appendChild(firstChild);
        
            var secondChild = document.createElement('div');
            secondChild.style.margin = '5px';
            secondChild.style.width = '18px';
            secondChild.style.height = '18px';
            secondChild.style.backgroundImage = 'url(<%= asset_path('mylocation-sprite-1x.png') %>)';
            secondChild.style.backgroundSize = '180px 18px';
            secondChild.style.backgroundPosition = '0px 0px';
            secondChild.style.backgroundRepeat = 'no-repeat';
            secondChild.id = 'you_location_img';
            firstChild.appendChild(secondChild);
        
        
          // Setup the click event listeners: simply set the map to Chicago.
          /*firstChild.addEventListener('click', function() {
            map.setZoom(17);
            map.panTo(persona);
          });*/
          firstChild.addEventListener('click', function() {
            //map.setZoom(17);
            map.panTo(persona);
            google.maps.event.addListenerOnce(map, 'idle', function() {
              map.setZoom(17);
            });
            if (mv == 0) {
              $('#you_location_img').css('background-position', '-144px 0px');
            } else {
              $('#you_location_img').css('background-position', '-162px 0px');
            }
            mv = 1;
          });
          
          firstChild.addEventListener('mouseover', function() {
            if (mv == 0) {
              $('#you_location_img').css('background-position', '-36px 0px');
            } else {
              $('#you_location_img').css('background-position', '-162px 0px');
            }
          });
          
          firstChild.addEventListener('mouseout', function() {
            if (mv == 0) {
              $('#you_location_img').css('background-position', '0px 0px');
            } else {
              $('#you_location_img').css('background-position', '-144px 0px');
            }
          });
          
          firstChild.addEventListener('mousedown', function() {
            if (mv == 0) {
              $('#you_location_img').css('background-position', '-54px 0px');
            } else {
              $('#you_location_img').css('background-position', '-162px 0px');
            }
          });
          
          firstChild.addEventListener('mouseup', function() {
            if (mv == 0) {
              $('#you_location_img').css('background-position', '-36px 0px');
            } else {
              $('#you_location_img').css('background-position', '-162px 0px');
            }
          });
          
          google.maps.event.addListener(map, 'dragend', function() {
              $('#you_location_img').css('background-position', '0px 0px');
              mv = 0;
          });
        
        }
        
        function CenterControl2(controlDiv2, map, sagar) {
        
          // Set CSS for the control border.
          var firstChild2 = document.createElement('button');
            firstChild2.style.backgroundColor = '#fff';
            firstChild2.style.border = 'none';
            firstChild2.style.outline = 'none';
            firstChild2.style.width = '28px';
            firstChild2.style.height = '28px';
            firstChild2.style.borderRadius = '2px';
            firstChild2.style.boxShadow = '0 1px 4px rgba(0,0,0,0.3)';
            firstChild2.style.cursor = 'pointer';
            firstChild2.style.marginRight = '10px';
            firstChild2.style.padding = '0px';
            firstChild2.title = 'Sidreria';
            controlDiv2.appendChild(firstChild2);
        
            var secondChild2 = document.createElement('div');
            secondChild2.style.margin = '5px';
            secondChild2.style.width = '18px';
            secondChild2.style.height = '18px';
            secondChild2.style.backgroundImage = 'url(<%= asset_path('logo_transp18.png') %>)';
            secondChild2.style.backgroundSize = '18px 18px';
            secondChild2.style.backgroundPosition = '0px 0px';
            secondChild2.style.backgroundRepeat = 'no-repeat';
            secondChild2.id = 'cider_location_img';
            firstChild2.appendChild(secondChild2);
        
        
          // Setup the click event listeners: simply set the map to Chicago.
          firstChild2.addEventListener('click', function() {
            //map.setZoom(17);
            map.panTo(sagar);
            google.maps.event.addListenerOnce(map, 'idle', function() {
              map.setZoom(17);
            });
          });
        
        }
          
          
          
        function myMap() {
          
          var directionsService = new google.maps.DirectionsService;
          var directionsDisplay = new google.maps.DirectionsRenderer;
          var infowindow = new google.maps.InfoWindow(); 
          //Creando el mapa
          var mapCanvas = document.getElementById("map");
          var mapOptions = {
            streetViewControl: true,
            mapTypeControl: true,
            zoomControl: true,
            //scaleControl: true,
            //rotateControl: true,
            center: new google.maps.LatLng(<%= @place.latitude %>,<%= @place.longitude %>), 
            zoom: 17,
            scrollwheel: false
          };
          var map = new google.maps.Map(mapCanvas, mapOptions);
          directionsDisplay.setMap(map);
          directionsDisplay.setOptions( { suppressMarkers: true } );
          
          
          //Creando los iconos
          var kupImg="<%= asset_path('logoblanco35.png') %>";
          //var kupImg="https://kupelike-oalba.c9users.io/img/botellasidra2.png";
      		var sagarImg={
      			url:kupImg,
      			size: new google.maps.Size(35, 35)
      		};
  		
      		var perImg="<%= asset_path('personaPos.png') %>";
      		//var perImg="https://kupelike-oalba.c9users.io/img/personaPos.png";
      		var persImg={
      			url:perImg,
      			size: new google.maps.Size(35, 35)
      		};
  		
  		    //Colocando marcadores
          var sagarPos = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
          var sagardotegi = new google.maps.Marker({
            position: sagarPos,
            animation: google.maps.Animation.DROP,
            map: map,
            title: '<%= @place.name %>',
            icon: sagarImg
          });
          var centerControl2 = new CenterControl2(centerControlDiv2, map, sagarPos);
          
          infowindow.setContent('<a href="google.navigation:q=<%= @place.latitude %>,<%= @place.longitude %>"><%= @place.name %><br><%= @place.address %></a>');
          sagardotegi.addListener('click', function() {
            infowindow.open(map, sagardotegi);
            map.panTo(sagardotegi.position);
            //map.setCenter(sagardotegi.position);
          });
          
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var perPos = {
                lat: position.coords.latitude,
                lng: position.coords.longitude
              };
              var persona = new google.maps.Marker({
                position: perPos,
                animation: google.maps.Animation.DROP,
                map: map,
                title: 'Tu posición.',
                icon: persImg
              });
              var centerControl = new CenterControl(centerControlDiv, map, perPos);
            });
          }
  
          calculateAndDisplayRoute(directionsService, directionsDisplay);
          centerControlDiv.index = 1;
          map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(centerControlDiv);
          centerControlDiv2.index = 1;
          map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(centerControlDiv2);
        }
        
        function calculateAndDisplayRoute(directionsService, directionsDisplay) {
          var sagarPos = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var perPos = {
                lat: position.coords.latitude,
                lng: position.coords.longitude
              };
              
              directionsService.route({
                origin: perPos,
                destination: sagarPos,
                travelMode: google.maps.TravelMode.DRIVING
              }, function(response, status) {
                if (status === google.maps.DirectionsStatus.OK) {
                  directionsDisplay.setDirections(response);
                } else {
                  window.alert('Fallo al mostrar la dirección ' + status);
                }
              });
            });
          }
        }
          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQWPiW2qkBRj4BXmEwFS2XMm2kzwKH82M&callback=myMap"></script>
    </div>
  </div>

app/views/places/show.html.erb
   <div class="container">
        <%= render 'facebook' %>
        <div class="row single-sagardotegi">
            <div class="col-xs-6">
                <h1 class="card-title text-uppercase"><%= @place.name %></h1>
                    <p class="single-description" id="descripcion"><%= @place.description %></p>
                    <p class="single-description" id="descripcion"><%= @place.time %></p>
                    <%= link_to map_path(@place.id) do %>
                      <button type="button" class="btn btn-default"><%= t('paginas.sidrerias.llegar') %></button>
                    <% end %>
                    <button id="contactoSidreria" type="button" class="btn btn-default"><%= t('paginas.sidrerias.contacto') %></button>
                    <div id="mostrarcontacto">
                        <p class="single-description"><%= @place.address %></p>
                        <a href="mailto:<%= @place.email %>"><p class="single-description"><%= @place.email %></p></a>
                        <a href="tel:<%= @place.phone %>"><p class="single-description"><%= @place.phone %></p></a> 
                    </div>
            </div>
            <div class="col-xs-6">
                <div class="card-single-direction text-uppercase text-center"><h4><%= @place.town %></h4></div>
                <img class="single-img img-responsive img-rounded" src="<%= @place.picture %>"></img>
            </div>
        </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
    
<div class="container-fluid">
        
    <div class="row p-x-1 kupela-list">
        <div class="col-xs-12 col-md-8 col-md-offset-2 col-xl-6 col-xl-offset-3">
          <%= render @place.items %>
        </div>
        
    </div>
<!-- <script type="text/javascript">
      
      window.onload = function () {
        var kupelasid = [];
         var kupelaslikes = [];
         //var hombres2 = 0;
         var kupelah = [];
         var kupelam = [];


        var chart = [];
        // var chart2 = [];
        var anonimous;
        for (i = 0; i < kupelasid.length; i++) {
        anonimous = kupelaslikes[i] - kupelam[i] - kupelah[i];
        chart[i] = new CanvasJS.Chart("chartContainer-"+kupelasid[i], {
                theme: "theme2",//theme1
                //width: 350,
                title:{
                    text: "Likes a la kupela por GENERO"              
                },
                animationEnabled: false,   // change to true
                data: [              
                {
                    // Change type to "bar", "area", "spline", "pie",etc.
                    type: "pie",
                    dataPoints: [
                        
                        { y: kupelam[i], label: "Women" },
                        { y: kupelah[i], label: "Men" },
                        { y: anonimous, label: "Anonimous" }
                        
                    ]
                }
                ]
            });
            chart[i].render();
          }
            
            
        //anonimous = kupelaslikes - kupelam - kupelah;
        // chart2 = new CanvasJS.Chart("chartContainer2-"+kupelaid, {
        //         theme: "theme2",//theme1
        //         //width: 350,
        //         title:{
        //             text: "Likes a la kupela por FECHA"              
        //         },
        //         animationEnabled: false,   // change to true
        //         data: [              
        //         {
        //             // Change type to "bar", "area", "spline", "pie",etc.
        //             type: "column",
        //             dataPoints: [

        //             ]
        //         }
        //         ]
        //     });
        //     {% for fecha in fechas %}
        //         if (kupelasid == {{fecha.id}}){
        //             chart2.options.data[0].dataPoints.push({ label: "{{fecha.fecha}}",  y: {{fecha.NumVotos}} });
        //         }
        //     {% endfor %}
        //     chart2.render();
            
        }
        
      
      </script> -->